version: '3.1'
services:
  API:
    image: 'duykypaul/spring-boot-jpa-postgresql-common'
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresql:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/postgres-data
    ports:
      - "7000:5432"
    restart: always
volumes:
  postgres-data:
