version: '3.1'

networks:
  paint-network:
    driver: bridge

volumes:
  dir-site:
  postgres-data:

services:
  springboot:
    container_name: spring_boot_jpa_postgresql
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    networks:
      - paint-network
    volumes:
      - dir-site:/home/sites
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSql:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSql:
    image: postgres:latest
    networks:
      - paint-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/postgres-data
    ports:
      - "7000:5432"
    restart: always
