version: '3.1'

networks:
  paint-network:
    driver: bridge

volumes:
  postgres-data:

services:
  API:
    image: 'duykypaul/spring-boot-jpa-postgresql-common'
    container_name: 'spring_boot_common_api'
    ports:
      - "8080:8080"
    networks:
      - paint-network
    depends_on:
      - PostgreSql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSql:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSql:
    image: postgres:latest
    container_name: 'spring_boot_common_postgres'
    networks:
      - paint-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/postgres-data
    ports:
      - "5432:5432"
    restart: always
