version: '3.1'

networks:
  paint-network:
    driver: bridge

volumes:
  postgres-data:

services:
  PaintHouse:
    image: 'duykypaul/paint-house'
    container_name: 'paint_house'
    ports:
      - "8080:8080"
    networks:
      - paint-network
    depends_on:
      - PostgreSql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PaintHouseDB:5432/paint_house
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PaintHouseDB:
    image: postgres:latest
    container_name: 'paint_house_postgres'
    networks:
      - paint-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=paint_house
      - PGDATA=/var/lib/postgresql/data/postgres-data
    ports:
      - "5432:5432"
    restart: always
