name: Build Docker & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

  dockerize:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: 'duykypaul/spring-boot-jpa-postgresql-common'
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs:
      - dockerize
    steps:
      - name: Deploy app to server
        uses: appleboy/ssh-action@master
        with:
          host: 103.179.175.62
          port: 22
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script_stop: true
          script: |
            docker container stop spring-boot-jpa-postgresql-common-app || true
            docker container rm spring-boot-jpa-postgresql-common-app || true
            docker image rm duykypaul/spring-boot-jpa-postgresql-common:latest || true
            docker pull duykypaul/spring-boot-jpa-postgresql-common:latest
            docker run -d -p 8080:8080 --network postgres_paint-network --name spring-boot-jpa-postgresql-common-app duykypaul/spring-boot-jpa-postgresql-common:latest