name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: duykypaul/spring-boot-jpa-postgresql-common
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Deploy app to server
      uses: appleboy/ssh-action@master
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      with:
        host: ${{ secrets.VPS_SSH_HOST }}
        port: ${{ secrets.VPS_SSH_PORT }}
        username: ${{ secrets.VPS_SSH_USERNAME }}
        password: ${{ secrets.VPS_SSH_PASSWORD }}
        script_stop: true
        script: |
          docker pull duykypaul/spring-boot-jpa-postgresql-common:latest
          docker container stop spring-boot-jpa-postgresql-common || true
          docker run -d --rm -p 8000:8000 --name spring-boot-jpa-postgresql-common duykypaul/spring-boot-jpa-postgresql-common:latest
