name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

  dockerize:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the stack1
        run: docker-compose up
      - name: Build the stack1
        run: docker-compose push

#  deploy:
#    runs-on: ubuntu-latest
#    continue-on-error: false
#    needs: [ dockerize ]
#    steps:
#      - name: Deploy app to server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.VPS_SSH_HOST }}
#          port: 22
#          username: duykypaul
#          password: ${{ secrets.VPS_SSH_PASSWORD }}
#          script_stop: true
#          script: |
#            docker pull duykypaul/spring-boot-jpa-postgresql-common:latest
#            docker container stop spring-boot-jpa-postgresql-common || true
#            docker run -d --rm -p 8080:8080 --name spring-boot-jpa-postgresql-common duykypaul/spring-boot-jpa-postgresql-common:latest
